apiVersion: apps/v1
kind: Deployment
metadata:
  name: flink
spec:
  selector:
    matchLabels:
      app: flink
  replicas: 1
  template:
    metadata:
      labels:
        app: flink
    spec:
      containers:
      - name: flink
        image: 119.253.86.183:18080/hadoop/book2/flink:1.7
        tty: true
        ports:
        - containerPort: 8081
