apiVersion: apps/v1
kind: Deployment
metadata:
  name: Flink
spec:
  selector:
    matchLabels:
      app: Flink
  replicas: 1
  template:
    metadata:
      labels:
        app: Flink
    spec:
      containers:
      - name: flink
        image: 119.253.86.183:18080/hadoop/book2/flink:1.7
        ports:
        - containerPort: 80