apiVersion: v1
kind: Service
metadata:
  name: hbase-master
spec:
  type: NodePort
  selector:
    app: hbase-master

  ports:
  - name: "50070"
    port: 50070
    targetPort: 50070
  - name: "8088"
    port: 8088
    targetPort: 8088
  - name: "8080"
    port: 8080
    targetPort: 8080
  - name: "8042"
    port: 8042
    targetPort: 8042
  - name: "16010"
    port: 16010
    targetPort: 16010
  - name: "7077"
    port: 7077
    targetPort: 7077
  - name: "4040"
    port: 4040
    targetPort: 4040
  - name: "10002"
    port: 10002
    targetPort: 10002
  - name: "5000"
    port: 5000
    targetPort: 5000
  - name: "54310"
    port: 54310
    targetPort: 54310



