apiVersion: apps/v1
kind: Deployment
metadata:
  name: redis
spec:
  selector:
    matchLabels:
      app: redis
  replicas: 1
  template:
    metadata:
      labels:
        app: redis
    spec:
      containers:
      hostname: redis
      - name: redis
        image: 119.253.86.183:18080/hadoop/book2/redis:5.0
        tty: true
        ports:
        - containerPort: 6379
