apiVersion: apps/v1
kind: Deployment
metadata:
  name: zoo1
spec:
  selector:
    matchLabels:
      app: zoo1
  replicas: 1
  template:
    metadata:
      labels:
        app: zoo1
    spec:
      hostname: zoo1
      containers:
      - env:
          - name: ZOO_MY_ID
            value: "1"
        name: zoo1
        image: 119.253.86.183:18080/hadoop_plus/book2/zookeeper:3.4.13
        tty: true