apiVersion: apps/v1
kind: Deployment
metadata:
  name: zoo3
spec:
  selector:
    matchLabels:
      app: zoo3
  replicas: 1
  template:
    metadata:
      labels:
        app: zoo3
    spec:
      hostname: z003
      containers:
      - env:
          - name: ZOO_MY_ID
            value: "3"
        name: zoo3
        image: 119.253.86.183:18080/hadoop_plus/book2/zookeeper:3.4.13
        tty: true